### ISSUE TITLE
Simple edit example :: "7_allTogether.html" to es5?

### ISSUE THREAD

**Issue by Thundros** [yomotsu/meshwalk.js#4]
Hi,` Yomotsu. This is an EXCELLENT library & AWESOME demos, but can you make a simple edit to 7_allTogether.html that changes the es6 to es5? es6 & promises & I don't mix. :(

like instead of : 

```javascript
Promise.all( [
  loadMesh( 'terrain.json' ),
  loadMesh( 'model/miku.json' )
] ).then( function( result ) {
```

I want to be able to do : 

```javascript
var mymesh = loadMesh ( 'terrain.json' );
var mymesh2 = loadMesh ( 'miku.json' );
mymesh.position.x = 0.0;
mymesh.position.y = 0.0;
mymesh.position.z = 0.0;
mymesh2.scale.x = 1.0;
mymesh2.scale.y = 1.0;
mymesh2.scale.z = 1.0;
```

Thank you once again, @yomotsu !

Peace brother

*~ Thundros

**Comment by yomotsu** [comment]
@Thundros thanks for trying. Loading external file(s) cannot be synchronous function, such as Ajax, isnt it?
How about just use Polyfill for Promise? like [es6-promise.auto.js](https://github.com/stefanpenner/es6-promise)? That can be use [via CDN](https://cdnjs.com/libraries/es6-promise) as well.

**Comment by Thundros** [comment]
No problem at all! I will continue to beta test it because I absolutely LOVE it! <3 So I figured out a way around the above problem but am stuck with the ONE problem stopping me from achieving anything in my own demo & that is the ability to use this EXACT camera with the tween library :: 
https://github.com/joates/3rd-person-cam-easing and this demo's ability to slowly rotate the character but allow for the camera to tween ( also in this demo by joates ). If there is a smooth tweening camera that can do what the link to the demo I have given does, this should be 100%! <3 I am willing to beta test if you can help add this small feature from above mentioned demo! Thanks again @yomotsu for ALL that you do! I've ALWAYS admired your work! <3

*~ Thundros

**Comment by yomotsu** [comment]
Thank you again for your cooperation.
I guess that can be done with pure three.js camera.

1. prepare 2 cameras
2. Animate 1st camera with `camera.lookAt()` and render your scene with the camera.
3. when the animation ended, swap the 1st camera with 2nd camera(which is TFP camera), and render scene with TPS camera

**Comment by Thundros** [comment]
I apologize whole-heartedly. I do not understand. I just want to use the camera from https://github.com/joates/3rd-person-cam-easing in this demo.

**Comment by Thundros** [comment]
That's all I meant. <3

**Comment by yomotsu** [comment]
You can use any camera whatever.
Although meshwalk.js provides TPSCameraControls, you dont need to use it.
Just use a camera (and cameraContorls) you prefer.

You might need to learn about three.js little bit more

**Comment by Thundros** [comment]
I actually figured it out. Just out of curiosity though, how would I rotate the character instead of making the character face a certain direction? I noticed you had a "turn(rad, immediate)" function, how would I call that function inside the library itself in order to assign the left & right arrow keys to it? Thanks ALOT, @yomotsu ! You are a TREMENDOUS help! :)

**Comment by Thundros** [comment]
I have tried everything for the above question. I can't figure out why I'm falling through the terrain when I scale it bigger than 2, 2, 2. What to do? Thanks again @yomotsu !

~*Thundros
